### ISSUE TITLE
Provenance Graph Generation

### ISSUE THREAD

**Issue by kunzeng-ch** [mayakapoor/flake#1]
Hello! I would like to know if it is possible to use this tool to turn the system trace log into a provenance graph。

**Comment by mayakapoor** [comment]
Hey,

I do think this would be possible. What tool are you using to get this system trace log? You would just need to write a filter implementation (see src/flurryflake/filters/filters.py for parent, src/flurryflake/filters/filters/w3cfilter.py for implementation) that is based on that tool's syntax. If loaded this library can build the internal graph and you can output it according to the various output options.

**Comment by kunzeng-ch** [comment]
I use sysdig to trace the log for system. Do you think you can use this tool to build its  provenance graph?

**Comment by kunzeng-ch** [comment]
Can you give an example, that is, there is a file containing log data, and then there are steps on how to generate a provenance graph of this log data through this tool
